version: '3.8'

services:  # <--- backend et db doivent être décalés sous cette ligne
  
  backend:
    build: .
    ports:
      - "7001:7001"
    depends_on:
      - db
    environment:
      - DB_HOST=db       # Indispensable pour ton nouveau code Java
      - DB_PORT=3306

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clicknwok
      restart: on-failure
    ports:
      - "3306:3306" # Ou 3307:3306 si tu as changé
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: