name: CI/CD Docker Pipeline

on:
  push:
    branches:
      - main
      - master  # Au cas où ta branche s'appelle master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installation de Java 17 (pour Maven)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Compilation du projet avec Maven
      # On saute les tests (-DskipTests) car GitHub n'a pas ta base de données lancée
      - name: Build with Maven
        run: mvn -B package -DskipTests --file api-users/pom.xml

      # 4. Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Construction et Envoi de l'image (Build & Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api-users     # On indique que le Dockerfile est dans ce dossier
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/api-users-backend:latest